### ISSUE TITLE
MediaPlayer Framework

### ISSUE THREAD

**Issue by KevinPy** [thermodo/ThermodoSDK#10]
Hello,
I try to run my Thermodo on my iPhone without going through CocoaPods, and I had a recurring problem, it never worked. 

I did not have much time to look, but I just noticed it had added another framework for this to work (at least, in my case). We must add the MediaPlayer framework. By adding the recommended framework (CoreAudio, AudioToolbox, AVFoundation), I could not manage to launch the application. 

Unless this issue has already been discussed, in which case it is a doublet, I think it should be added that framework.

**Comment by simonbs** [comment]
We have added the Media Player framework as a dependency in the Podspec. This has also been merged into the CocoaPods specs repository. 9981b97a13ba2d2cd17760c91a61ee5591a23f36

Thanks for making us aware of this issue.
