### ISSUE TITLE
Memory leak during normal running

### ISSUE THREAD

**Issue by destari** [thermodo/ThermodoSDK#13]
I have enabled this on a device in which will be away from touch for a year-ish, and so memory leaks are a serious problem.  The SDK leaks memory and after a few hours of running makes the app get killed (a few hundred MB of leakage).

**Comment by simonbs** [comment]
Thank you for reporting the issue. I was to reproduce a memory leak, however, I did find that the SDK would consume an extreme amount of memory. This issue has been addressed in 1.1.1. Please try the updated version and verify that this solves your issue.

**Comment by destari** [comment]
It actually still leaks slowly.  It also now crashes too on occasion, and continuously eats a huge amount of CPU.
