### ISSUE TITLE
Apple Headset recognized as Thermodo in Mac SDK

### ISSUE THREAD

**Issue by fnky** [thermodo/ThermodoSDK#14]
Thermodo SDK for Mac on Mac OS X 10.10 (Yosemite)

The SDK worked, but to an extend that it would recognize my Apple Headset (EarPods from 2012) would make a beeping sound with an interval, as if it was the Thermodo measuring the temperature OR test to determine if it's a Thermodo or just a headset.

The `thermodoDidRejectInput:` method is not called when I plug in the EarPods.

Note: I haven't tested if an actual Thermodo works, but will test soon.

**Comment by simonbs** [comment]
The detection is currently only supported in the iOS SDK. We hope to add support for detection in the OS X SDK in the future.
Therefore, it is expected that `thermodoDidRejectInput:` is not called as the OS X SDK does not try to determine if the input is in fact a Thermodo but currently accepts (almost) any input in the audio jack.
