### ISSUE TITLE
Calling -stop while Thermodo is measuring causes an exception

### ISSUE THREAD

**Issue by henrinormak** [thermodo/ThermodoSDK#2]
Calling -stop right after Thermodo has read its' first value (or in fact any value, as long as isMeasuring is true) will cause an exception.

Added the library manually.

```
2013-12-18 22:18:28.665 Shade[1265:60b] -[AVAudioSession setActive:]: unrecognized selector sent to instance 0x15586430
2013-12-18 22:18:28.669 Shade[1265:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AVAudioSession setActive:]: unrecognized selector sent to instance 0x15586430'
*** First throw call stack:
(0x2feb3e83 0x3a2146c7 0x2feb77b7 0x2feb60af 0x2fe04dc8 0x14d067 0xb7107 0x14d7cf 0x3a6f90c3 0x3a6f90af 0x3a6fb9a9 0x2fe7e5b1 0x2fe7ce7d 0x2fde7471 0x2fde7253 0x34b1b2eb 0x3269c845 0x65bf9 0x3a70dab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by henrinormak** [comment]
Actually, seems like calling `-stop` will always cause the same exception. Even if there is no Thermodo connected, even if there is a call to `-start` first and so on. Seems like a pretty serious bug, please let me know if there is anything I can do to help you sort it out.

**Comment by ulrikdamm** [comment]
I actually just fixed this error today. There'll probably be a bug fix update to the SDK this week.

**Comment by henrinormak** [comment]
Any update on this, an ETA perhaps for when the fix would be commited? We would like to include Thermodo support in our app (http://shadeapp.com), but we most definitely need the stopping functionality to be there.

**Comment by ulrikdamm** [comment]
Sorry for the delay, the update will be available later today.

**Comment by ksmandersen** [comment]
The latest version 1.0.1 resolves this issue.
