### ISSUE TITLE
Podspec includes frameworks that it does not need to add

### ISSUE THREAD

**Issue by henrinormak** [thermodo/ThermodoSDK#3]
Podspec should remove this line

`s.frameworks = [ 'AVFoundation', 'AudioUnit', 'AudioToolbox', 'UIKit', 'CoreGraphics' ]`

This is not needed, otherwise the manual installation would also need to note that linking to those frameworks is needed. With this line kept getting a linker error, without it, workspace compiles fine.

**Comment by ksmandersen** [comment]
These frameworks are actually required at the moment. This is, however, going to change soon

**Comment by henrinormak** [comment]
Interesting you say that, the application compiled fine without having those frameworks in there and produced a linker error with them. Any ideas why was that?
