### ISSUE TITLE
Constant 0 temperature on iPhone 5s

### ISSUE THREAD

**Issue by henrinormak** [thermodo/ThermodoSDK#9]
Current release 1.0.2 returns temperature as a constant 0 on the 5S, works fine on iPod Touch and 4S. Might have to do with 64-bit architecture, but difficult to tell without the source code.

Any ETA on the fix would be appreciated.

**Comment by caidurbin** [comment]
I'm also seeing this issue with my iPhone 5S but I've discovered a (less than ideal) workaround. 

In the Build Settings for the app target, change the architectures setting from
"Standard architectures (including 64-bit) (armv7, armv7s, arm64)"
to
"Standard architectures (armv7, armv7s)"

As @henrinormak suggested, this issue does seem to be related to the 64-bit architecture. You might not be seeing this issue if all your test projects were created before arm64 support was the default.

**Comment by ulrikdamm** [comment]
Okay, I think I've found the problem, and it's a pretty easy fix. The method signature for -thermodo:didGetTemperature: in the delegate protocol used the type CGFloat, while a normal float is used in the implementation. We'll send out an update soon, but a temporary fix is to just change the line

``` Objective-C
- (void)thermodo:(THMThermodo *)thermodo didGetTemperature:(CGFloat)temperature;
```

in the THMThermodo.h file to

``` Objective-C
- (void)thermodo:(THMThermodo *)thermodo didGetTemperature:(float)temperature;
```

Please let me know if this fixes the problem for you.

**Comment by henrinormak** [comment]
Of course, that explains why I was seeing values slightly larger than 0 when debugging, thanks for the tip and for the fix! :+1:

**Comment by caidurbin** [comment]
Yep, that fixes it for me too. Thanks @ulrikdamm

**Comment by ksmandersen** [comment]
Updated to version 1.0.3 where this issue is fixed
